#!/usr/bin/env python


data = open('ripple_function_dB.txt')
ripplea = [float(x.strip()) for x in data.readlines()]

ripple1 = [value - 0.2 for value in ripplea]
ripple2 = [value + 1.7 for value in ripplea]
ripple3 = [value - 0.4 for value in ripplea]
ripple4 = [value + 0.7 for value in ripplea]
ripple5 = [value + 0.5 for value in ripplea]
ripple6 = [value + 1.5 for value in ripplea]
ripple7 = [value + 1.8 for value in ripplea]
ripple8 = [value + 1.9 for value in ripplea]


new_file1 = open('ripple_altered_a.txt', 'a')
for value in ripple1:
	new_file1.write(str(value) + '\n')

new_file1 = open('ripple_altered_b.txt', 'a')
for value in ripple2:
	new_file1.write(str(value) + '\n')

new_file1 = open('ripple_altered_c.txt', 'a')
for value in ripple3:
	new_file1.write(str(value) + '\n')

new_file1 = open('ripple_altered_d.txt', 'a')
for value in ripple4:
	new_file1.write(str(value) + '\n')

new_file1 = open('ripple_altered_e.txt', 'a')
for value in ripple5:
	new_file1.write(str(value) + '\n')

new_file1 = open('ripple_altered_f.txt', 'a')
for value in ripple6:
	new_file1.write(str(value) + '\n')

new_file1 = open('ripple_altered_g.txt', 'a')
for value in ripple7:
	new_file1.write(str(value) + '\n')

new_file1 = open('ripple_altered_h.txt', 'a')
for value in ripple8:
	new_file1.write(str(value) + '\n')


#########################################################################
data = open('ripple_wyang.txt')
ripplea = [float(x.strip()) for x in data.readlines()]

ripple1 = [value + 2.0 for value in ripplea]
ripple2 = [value - 0.1 for value in ripplea]
ripple3 = [value + 1.4 for value in ripplea]
ripple4 = [value - 0.2 for value in ripplea]
ripple5 = [value + 1.8 for value in ripplea]
ripple6 = [value - 1.2 for value in ripplea]
ripple7 = [value + 1.7 for value in ripplea]
ripple8 = [value - 1.5 for value in ripplea]
ripple9 = [value + 1.3 for value in ripplea]
ripple10 = [value + 1.5 for value in ripplea]
ripple11 = [value + 1.6 for value in ripplea]

new_file1 = open('wyang_3a.txt', 'a')
for value in ripple1:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3b.txt', 'a')
for value in ripple2:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3c.txt', 'a')
for value in ripple3:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3d.txt', 'a')
for value in ripple4:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3e.txt', 'a')
for value in ripple5:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3f.txt', 'a')
for value in ripple6:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3g.txt', 'a')
for value in ripple7:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3h.txt', 'a')
for value in ripple8:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3i.txt', 'a')
for value in ripple9:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3j.txt', 'a')
for value in ripple10:
	new_file1.write(str(value) + '\n')

new_file1 = open('wyang_3k.txt', 'a')
for value in ripple11:
	new_file1.write(str(value) + '\n')