#!/usr/bin/env python
import matplotlib.pyplot as plt
import numpy as np
import math
import matplotlib.patches as mpatches

data = open('ripple_wyang.txt')
rippleo = [float(x.strip()) for x in data.readlines()]

data = open('ripple_function_dB.txt')
ripple_function_dB = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3a.txt')
ripplea = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3b.txt')
rippleb = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3c.txt')
ripplec = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3d.txt')
rippled = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3e.txt')
ripplee = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3f.txt')
ripplef = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3g.txt')
rippleg = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3h.txt')
rippleh = [float(x.strip()) for x in data.readlines()]


# new
data = open('wyang_3i.txt')
ripplei = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3j.txt')
ripplej = [float(x.strip()) for x in data.readlines()]

data = open('wyang_3k.txt')
ripplek = [float(x.strip()) for x in data.readlines()]
##

data = open('ripple_altered_a.txt')
ripple_altered_a = [float(x.strip()) for x in data.readlines()]

data = open('ripple_altered_b.txt')
ripple_altered_b = [float(x.strip()) for x in data.readlines()]

data = open('ripple_altered_c.txt')
ripple_altered_c = [float(x.strip()) for x in data.readlines()]

data = open('ripple_altered_d.txt')
ripple_altered_d = [float(x.strip()) for x in data.readlines()]

data = open('ripple_altered_e.txt')
ripple_altered_e = [float(x.strip()) for x in data.readlines()]

# new
data = open('ripple_altered_f.txt')
ripple_altered_f = [float(x.strip()) for x in data.readlines()]

data = open('ripple_altered_g.txt')
ripple_altered_g = [float(x.strip()) for x in data.readlines()]

data = open('ripple_altered_h.txt')
ripple_altered_h = [float(x.strip()) for x in data.readlines()]


x = []
i = 0
for rf in ripple_function_dB:
	i = i + 1
	x.append(i)

time = np.arange(0, len(ripplea)*2, 5)
amplitude = np.sin(time)

plt.xlabel('Wavelength')
plt.ylabel('Ripple function')
plt.axis([1,90, -2, 4])
plt.grid(True)
plt.plot(x, ripple_function_dB)
plt.plot(x, rippleo)
plt.plot(x, ripplea)
plt.plot(x, rippleb)
plt.plot(x, ripplec)
plt.plot(x, rippled)
plt.plot(x, ripplee)
plt.plot(x, ripplef)
plt.plot(x, rippleg)
plt.plot(x, rippleh)
plt.plot(x, ripplei)
plt.plot(x, ripplej)
plt.plot(x, ripplek)
plt.plot(x, ripple_altered_a)
plt.plot(x, ripple_altered_b)
plt.plot(x, ripple_altered_c)
plt.plot(x, ripple_altered_d)
plt.plot(x, ripple_altered_e)
plt.plot(x, ripple_altered_f)
plt.plot(x, ripple_altered_g)
plt.plot(x, ripple_altered_h)
# plt.plot(time, amplitude)
plt.show()
